Major Music Functionality Addition
yingren-wang/CS499-slideshow pull request #44
Opened 2020-03-24 02:46 UTC by F1shOutaWater

*Music Functionality almost entirely there(Add, swap, remove, progress bar, etc)
*Update to GUI look plus additional buttons (honing in on final look and feel)

*TODO: 
*Progress bar has minor bug where on multiple tracks, the thread wants to die, or improper total time duration. 
*Also, AIFF tracks are proving very difficult to accomodate. They are NOT supported at this time.

2020-03-24 17:53 UTC, TheDeltaAgent requested changes
It says the only changes here are binary files when I imagine some actual stuff was changed. I really don't trust this. There are no changes to the form or class at all? Also do you have the class name change (SlideHandler to SlideShowHandler?)

2020-03-25 08:25 UTC, yingren-wang commented
Please change the pull request from merging into branch **slide-handler-class-branch** to branch **new-master**, since branch **new-master** has the merged change of:
1. Chandler's SlideShowHandler class (was named as SlideHandler)
2. Yingren's add slide to slideshow panel
3. Ethan's dropdown menu on picture box

So in branch **new-master**, it can add slide to slideshow panel by using Ethan's dropdown menu on the picture box. But the information like the slideList is not stored in the class SlideShowHandler yet.

2020-03-25 08:26 UTC, yingren-wang requested changes

2020-03-25 08:26 UTC, yingren-wang commented on Slide-by-Side_creator/creator/SlideHandler.cs
> +    public struct Slide
I thought we discussed about having both structs Slide and Soundtrack as variables under the class SlideShowHandler, so please put them back under the class SlideShowHandler. Correct me if I got it wrong, or please say the reason if you think this is a better choice.

2020-03-25 08:26 UTC, yingren-wang commented on Slide-by-Side_creator/creator/SlideHandler.cs
> +<<<<<<< HEAD
unresolved github merge reminder, please delete this.

2020-03-25 08:26 UTC, yingren-wang commented on Slide-by-Side_creator/creator/SlideHandler.cs
> +        private Slide[] slideList;
Wrong type of slideList, I think this is a previous mistake we had and it just happens to be here, please delete line 57 and line 58.

2020-03-25 08:30 UTC, yingren-wang commented
Please delete all the following files from the pull request:
(You can choose to save them locally, but please do not push them to the github repo)
1. .vs/
2. */Debug/ (including obj/Debug/.. and bin/Debug/..)
Thx

2020-03-25 18:37 UTC, yingren-wang requested changes

2020-03-25 18:37 UTC, yingren-wang commented on Slide-by-Side_creator/creator/Form1.cs
>          private System.Windows.Forms.Timer time = new System.Windows.Forms.Timer();
Is this variable the same as the private bool musicPlaying variable?
Please check line 39.

2020-03-26 20:07 UTC, F1shOutaWater commented on Slide-by-Side_creator/creator/SlideHandler.cs
> +    public struct Slide
We're going to put it outside :)

2020-04-28 05:32 UTC, closed without merging